### ISSUE TITLE
How to and should we identify and remove "bad/outlier" FCS files and not just events?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [giannimonaco/flowAI#14]
Hi there, 

Thanks for the package.

flowAI can help remove technical error by removing actual events, but not the whole FCS file (http://127.0.0.1:18637/library/flowAI/doc/flowAI.html). 

In my data, by manually examining the staining profile, I identified some FCS files that had "outlier" staining pattern (across markers) and aim to remove these FCS files from the clustering analysis, but is there a way to objectively remove certain whole FCS files instead of just visually deciding?

Or, is it a best practice to only remove outlier events and not the whole file?

Thank you again for your help.

**Comment by giannimonaco** [comment]
Hi,
Currently, flowAI does not automatically decide to remove whole FCS files.
it is best practice to only remove outliers from the FCS file.  In general,
flowAI only removes some outliers so that you can still use the rest of the
file and you do not have to completely discard the experiment.
However, after a visual check of the report, you could also decide to
completely discard the file, in case there are too many weird patterns,
some lasers did not work or any other important issue.

**Comment by denvercal1234GitHub** [comment]
Thank you very much for your response!
